-- Exemplo de inserção até 30 registros
INSERT INTO tb_operator(name) VALUES ('Dr. Lucas');
INSERT INTO tb_operator(name) VALUES ('Dra. Fernanda');
INSERT INTO tb_operator(name) VALUES ('Dr. Pedro');
INSERT INTO tb_operator(name) VALUES ('Dra. Camila');
INSERT INTO tb_operator(name) VALUES ('Dr. Rafael');
INSERT INTO tb_operator(name) VALUES ('Dra. Juliana');
INSERT INTO tb_operator(name) VALUES ('Dr. Marcos');
INSERT INTO tb_operator(name) VALUES ('Dra. Ana');
INSERT INTO tb_operator(name) VALUES ('Dr. Carolina');
INSERT INTO tb_operator(name) VALUES ('Dra. Rodrigo');
INSERT INTO tb_operator(name) VALUES ('Dr. Isabel');
INSERT INTO tb_operator(name) VALUES ('Dra. André');
INSERT INTO tb_operator(name) VALUES ('Dr. Bruna');
INSERT INTO tb_operator(name) VALUES ('Dra. Lucas');
INSERT INTO tb_operator(name) VALUES ('Dr. Patrícia');
INSERT INTO tb_operator(name) VALUES ('Dra. Gustavo');
INSERT INTO tb_operator(name) VALUES ('Dr. Vanessa');
INSERT INTO tb_operator(name) VALUES ('Dra. João');
INSERT INTO tb_operator(name) VALUES ('Dr. Mariana');
INSERT INTO tb_operator(name) VALUES ('Dra. Andréia');
INSERT INTO tb_operator(name) VALUES ('Dr. Paula');
INSERT INTO tb_operator(name) VALUES ('Dra. Tiago');
INSERT INTO tb_operator(name) VALUES ('Dr. Laura');
INSERT INTO tb_operator(name) VALUES ('Dra. Ricardo');
INSERT INTO tb_operator(name) VALUES ('Dr. Gabriela');
INSERT INTO tb_operator(name) VALUES ('Dra. Marcos');
INSERT INTO tb_operator(name) VALUES ('Dr. Letícia');
INSERT INTO tb_operator(name) VALUES ('Dra. Gustavo');
INSERT INTO tb_operator(name) VALUES ('Dr. Bianca');
INSERT INTO tb_operator(name) VALUES ('Dra. Lucas');

INSERT INTO tb_user(operator_id, name, email) VALUES (8, 'Ana', 'ana@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (13, 'Carlos', 'carlos@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (19, 'Julia', 'julia@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (5, 'Pedro', 'pedro@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (30, 'Luiza', 'luiza@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (9, 'Felipe', 'felipe@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (17, 'Mariana', 'mariana@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (27, 'Lucas', 'lucas@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (12, 'Gabriela', 'gabriela@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (4, 'Rafael', 'rafael@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (22, 'Paula', 'paula@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (10, 'Mateus', 'mateus@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (28, 'Camila', 'camila@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (15, 'Gustavo', 'gustavo@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (2, 'Fernanda', 'fernanda@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (26, 'Tiago', 'tiago@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (18, 'Isabela', 'isabela@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (6, 'Rodrigo', 'rodrigo@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (25, 'Amanda', 'amanda@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (14, 'Marcelo', 'marcelo@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (21, 'Vanessa', 'vanessa@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (29, 'Matheus', 'matheus@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (7, 'Jessica', 'jessica@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (20, 'Daniel', 'daniel@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (1, 'Patricia', 'patricia@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (11, 'Renato', 'renato@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (23, 'Larissa', 'larissa@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (3, 'Thiago', 'thiago@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (16, 'Carolina', 'carolina@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (24, 'José', 'jose@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (30, 'Luciana', 'luciana@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (8, 'Eduardo', 'eduardo@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (18, 'Natália', 'natalia@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (5, 'Vinicius', 'vinicius@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (29, 'Ana Paula', 'anapaula@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (14, 'Roberto', 'roberto@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (12, 'Tatiane', 'tatiane@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (27, 'Renata', 'renata@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (7, 'Leonardo', 'leonardo@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (26, 'Carla', 'carla@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (9, 'André', 'andre@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (16, 'Fernando', 'fernando@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (25, 'Sabrina', 'sabrina@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (6, 'Ricardo', 'ricardo@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (19, 'Monica', 'monica@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (8, 'Felipe', 'felipe@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (30, 'Aline', 'aline@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (2, 'Marcio', 'marcio@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (22, 'Tatiana', 'tatiana@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (4, 'João', 'joao@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (28, 'Luiz', 'luiz@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (15, 'Caroline', 'caroline@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (7, 'Lucas', 'lucas@hotmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (17, 'Manuela', 'manuela@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (27, 'Silvia', 'silvia@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (13, 'Diego', 'diego@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (3, 'Tais', 'tais@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (19, 'Cristiano', 'cristiano@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (5, 'Marina', 'marina@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (30, 'Raquel', 'raquel@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (8, 'Vitor', 'vitor@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (18, 'Isabel', 'isabel@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (6, 'Erika', 'erika@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (25, 'Renan', 'renan@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (14, 'Marcos', 'marcos@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (12, 'Bianca', 'bianca@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (27, 'Hugo', 'hugo@gmail.com');
INSERT INTO tb_user(operator_id, name, email) VALUES (7, 'Laura', 'laura@gmail.com');